import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),canvas=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');Object.assign(globalThis,{DOMMatrix:canvas.DOMMatrix,ImageData:canvas.ImageData,Path2D:canvas.Path2D});Uint8Array.prototype.toHex??=function(){return Buffer.from(this).toString('hex');};
const pdfjs=await import('../src/vendor/pdf.mjs');const {extractLines}=await import('../src/text-lines.mjs');const {appendLine}=await import('../src/line-geometry.mjs');const {matchTargets}=await import('../src/calibrate-worker.mjs');
const pdf=await pdfjs.getDocument({data:new Uint8Array(fs.readFileSync('../upload/巍山年鉴_2025_152.pdf')),isEvalSupported:false}).promise;
const cases=JSON.parse(fs.readFileSync(new URL('./fixtures/v10-calibration-anchors.json',import.meta.url)));
const pages={};for(const page of [...new Set(cases.map(c=>c.page))]){const lines=[...await extractLines(pdf,page,0),...await extractLines(pdf,page,0,{visualRows:true})];pages[page]=[];for(let i=0;i<lines.length;i++){let joined=lines[i];pages[page].push(joined);for(let j=1;j<=2&&i+j<lines.length;j++){const next=lines[i+j];if(Math.abs(next.left-joined.left)>15||next.top-joined.bottom>20||next.top<joined.top)break;joined=appendLine(joined,next);pages[page].push(joined);}}}
const results=matchTargets({nodes:cases.map((c,i)=>({id:String(i),title:c.title,target:{kind:'dest',page:c.page,mode:'XYZ',args:c.first}})),pages,offset:5,unit:'pt'});const report=[];
for(let i=0;i<cases.length;i++){const c=cases[i],r=results[i].candidates[0];assert(r,c.title);const delta=Math.hypot(c.heading[0]-r.target.args[0],c.heading[1]-r.target.args[1]);assert(delta<.15,`${c.title}: ${delta} pt; ${r.text}`);report.push({title:c.title,page:c.page,expected:c.heading,actual:r.target.args,errorPt:delta,evidence:r.evidence});}
fs.writeFileSync('tests/output/v10-calibration-report.json',JSON.stringify({checks:[`${report.length} known heading anchors match within 0.15 PDF point`],cases:report},null,2));console.log(report.length,'calibration anchors passed');await pdf.destroy();
