import fs from "node:fs";
import { PdfEngine } from "../src/pdf-core.mjs";
import { makeNode } from "../src/model.mjs";
const engine = new PdfEngine();
await engine.open(
  new Uint8Array(fs.readFileSync("tests/output/v5-300-pages.pdf")),
);
const contentBytes = new Uint8Array(
  fs.readFileSync("tests/output/v5-300-searchable.pdf"),
);
const nodes = [makeNode("最新书签", 36)],
  measure = [];
for (const [name, title] of [
  ["first", "最新书签"],
  ["bookmark-only", "已更新书签"],
]) {
  nodes[0].title = title;
  const started = performance.now();
  const bytes = await engine.save({
    contentBytes,
    nodes,
    metadata: { title: "内容缓存保存验证" },
    rotations: { 2: 90 },
  });
  measure.push({ name, ms: performance.now() - started, bytes: bytes.length });
  fs.writeFileSync("tests/output/v6-save-" + name + ".pdf", bytes);
}
fs.writeFileSync(
  "tests/output/v6-save-report.json",
  JSON.stringify(
    {
      pages: 300,
      ocrLines: 2400,
      nativeRebuildsOnSave: 0,
      measure,
      environment:
        "Linux Node; applied content generated by real Python sidecar",
    },
    null,
    2,
  ),
);
console.log(measure);
