const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const {NativeBridge}=require('../native-bridge.cjs'),{FlowLayout}=require('../flow-layout.cjs');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'tests/output');
const bridge=new NativeBridge(path.join(root,'native'),process.env.FOLIO_PYTHON||'python'),flow=new FlowLayout(path.join(root,'native'),process.env.FOLIO_PYTHON||'python');
let browser,page;const errors=[],checks=[];
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.FOLIO_CHROMIUM,args:['--no-sandbox','--disable-gpu','--disable-background-networking']});
 page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.hostname!=='localhost')return route.abort();try{
 let body,type='application/json';if(req.method()==='POST'){const data=JSON.parse(req.postData());const r=u.pathname==='/__flow'?await flow.render(data):await bridge.run(data);if(r.bytes)r.bytes=Array.from(r.bytes);body=JSON.stringify(r);}
 else{const file=path.resolve(root,'src','.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));body=fs.readFileSync(file);if(file.endsWith('/app.mjs'))body=Buffer.concat([body,Buffer.from('\nwindow.__qa={S,actions,loadPDF,closeModal,rebuild,commit};')]);type=({'.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(file)]||'application/octet-stream';}await route.fulfill({status:200,contentType:type,body});
 }catch(e){await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:e.message})});}});
 await page.addInitScript(()=>{const call=async(url,d)=>{const r=await fetch(url,{method:'POST',body:JSON.stringify(d)}),v=await r.json();if(v.error)throw Error(v.error);if(v.bytes)v.bytes=new Uint8Array(v.bytes);return v;};window.__saved=[];window.desktop={native:d=>call('/__native',{...d,...(d.bytes?{bytes:Array.from(d.bytes)}:{})}),qpdf:d=>call('/__native',{...d,bytes:Array.from(d.bytes)}),cancelQpdf(){},flowLayout:d=>call('/__flow',d),setDirty(){},onClose(){},onNativeProgress(){},graphics:async()=>false,copyText:async()=>{},save:async d=>{window.__saved.push({name:d.name,length:d.bytes.length,kind:d.kind});return {name:d.name}},ocrJob:async()=>[]};});
 await page.goto('http://localhost');await page.waitForFunction(()=>window.__qa);
 await page.evaluate(async bytes=>window.__qa.loadPDF(new Uint8Array(bytes),'QA.pdf'),Array.from(fs.readFileSync(path.join(out,'v11-fixture.pdf'))));
 await page.evaluate(()=>{const {S,rebuild}=window.__qa;S.nodes=[{id:'root',parent:null,title:'目录',color:'#000000',bold:false,italic:false,open:true,target:{kind:'dest',page:1,mode:'XYZ',args:[null,null,null]}},{id:'a',parent:'root',title:'第十二章',color:'#000000',bold:false,italic:false,open:true,target:{kind:'dest',page:1,mode:'XYZ',args:[null,null,null]}},{id:'b',parent:'root',title:'附录',color:'#000000',bold:false,italic:false,open:true,target:{kind:'dest',page:1,mode:'XYZ',args:[null,null,null]}}];rebuild();});
 const action=n=>page.evaluate(n=>window.__qa.actions[n](),n),close=()=>page.evaluate(()=>window.__qa.closeModal());
 await action('batch');await page.locator('#b-find').fill('^第(.*)章$');await page.locator('#b-replacement').fill('章节 $1');await page.locator('#b-case').check();await close();await action('batch');assert.equal(await page.locator('#b-find').inputValue(),'^第(.*)章$');assert.equal(await page.locator('#b-replacement').inputValue(),'章节 $1');assert(await page.locator('#b-case').isChecked());await close();checks.push('Batch expression, replacement, case restored after cancel/reopen');
 await page.locator('#filter-regex').click();await page.locator('#filter').fill('^第.*章$');await page.waitForFunction(()=>!document.querySelector('#filter-select').disabled);assert.equal(await page.evaluate(()=>window.__qa.S.visible.length),2);await page.locator('#filter-select').click();assert.deepEqual(await page.evaluate(()=>[...window.__qa.S.selected]),['a']);
 await page.locator('#filter-batch').click();assert.equal(await page.locator('#batch-scope').inputValue(),'filtered');await page.waitForFunction(()=>!document.querySelector('#batch-apply').disabled);await page.screenshot({path:path.join(out,'v11-rules.png')});await page.locator('#batch-apply').click();assert.equal(await page.evaluate(()=>window.__qa.S.nodes[1].title),'章节 十二');assert.equal(await page.evaluate(()=>window.__qa.S.nodes[0].title),'目录');checks.push('Regex filter shows ancestors; select/apply changes only true matches');
 await page.locator('#filter').fill('[');await page.waitForFunction(()=>document.querySelector('#filter').getAttribute('aria-invalid')==='true');assert(await page.locator('#filter-select').isDisabled());checks.push('Invalid regex keeps interface responsive and disables batch application');
 await page.evaluate(()=>{const {S,rebuild}=window.__qa;S.nodes=S.nodes.map(n=>n.id==='b'?{...n,title:'a'.repeat(20000)+'!'}:n);rebuild();});
 await page.locator('#filter').fill('^(a+)+$');await page.waitForFunction(()=>document.querySelector('#filter-status').textContent.includes('超过 2 秒'),null,{timeout:8000});assert(await page.locator('#filter-select').isDisabled());
 await page.evaluate(()=>{const {S,rebuild}=window.__qa;S.nodes=S.nodes.map(n=>n.id==='b'?{...n,title:'附录'}:n);rebuild();});checks.push('Pathological regex terminates after timeout without blocking main interface');
 await page.locator('#filter').fill('');await page.waitForTimeout(200);
 await action('decrypt');await page.locator('#decrypt-source').selectOption('original');await page.locator('#decrypt-export').click();await page.waitForFunction(()=>window.__saved.some(f=>f.name.endsWith('-decrypted.pdf')));assert.equal(await page.locator('#decrypt-password').inputValue(),'');await page.screenshot({path:path.join(out,'v11-decrypt.png')});await close();checks.push('Decrypt UI exports separate validated PDF and clears password');
 await action('flow-edit');await page.waitForSelector('.page-edit-hit');await page.locator('.page-edit-hit').first().click();await page.waitForFunction(()=>/原始字位完成/.test(document.querySelector('#pe-status')?.textContent),{timeout:60000});await page.screenshot({path:path.join(out,'v11-original-layout.png')});await page.locator('#pe-font').click();await page.locator('#pe-font-match').click();await page.waitForFunction(()=>!document.querySelector('#pe-font-match').disabled,{timeout:60000});await page.screenshot({path:path.join(out,'v11-font-match.png')});checks.push('Page editor uses original glyph coordinates; actual outline font recommendations render');
 await page.locator('#pe-close-font').click();await page.locator('#pe-done').click();assert.equal(await page.evaluate(()=>window.__qa.S.nativeEdits.length),0);checks.push('Entering/exiting editor without edits creates no content rewrite');
 await page.evaluate(async bytes=>window.__qa.loadPDF(new Uint8Array(bytes),'Table QA.pdf'),Array.from(fs.readFileSync(path.join(out,'v9-fixture.pdf'))));
 await action('table-structure');await page.waitForFunction(()=>!document.querySelector('#table-apply').disabled);await page.locator('[data-table-export="xlsx"]').click();await page.waitForFunction(()=>window.__saved.some(f=>f.kind==='xlsx'));await page.screenshot({path:path.join(out,'v11-table-export.png')});await close();checks.push('Reviewed table exports XLSX from UI without changing PDF');
 for(const width of [900,1440]){await page.setViewportSize({width,height:800});await action('batch');const boxes=await page.locator('#modal-footer button:visible').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return [r.left,r.right,r.bottom]}));assert(boxes.every(([l,r,b])=>l>=0&&r<=width+1&&b<=801));await close();}
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'v11-ui-report.json'),JSON.stringify({checks,errors,browser:await browser.version()},null,2));console.log(JSON.stringify({checks,errors}));
})().catch(async e=>{console.error(e);if(page){console.error('page errors',errors);console.error(await page.locator('#pe-status').textContent().catch(()=>''));await page.screenshot({path:path.join(out,'v11-ui-failure.png')});}process.exitCode=1}).finally(async()=>{await browser?.close();bridge.cancel();flow.close()});
