import fs from 'node:fs';
const en=JSON.parse(fs.readFileSync('src/locales/en.json','utf8'));
const zhHant=JSON.parse(fs.readFileSync('src/locales/zh-Hant.json','utf8'));
fs.writeFileSync('src/locales/catalog.mjs','// Generated by scripts/build-locales.mjs from reviewed offline catalogs.\nexport const en = '+JSON.stringify(en)+';\nexport const zhHant = '+JSON.stringify(zhHant)+';\n');
