from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'src/app.mjs';s=p.read_text();s='import {installNativeUI} from "./native-ui.mjs";\nimport {describeChanges} from "./changes.mjs";\n'+s;s=s.replace('annotations: [],','annotations: [], nativeEdits: [], ocr: [],');s=s.replace('annotations: S.annotations,\n    metadata:','annotations: S.annotations,nativeEdits:S.nativeEdits,ocr:S.ocr,\n    metadata:',1)
s=s.replace('function restore(v) {','async function restore(v) {').replace('  Object.assign(S, v);\n  setDirty','  if(JSON.stringify([v.nativeEdits||[],v.ocr||[]])!==JSON.stringify([S.nativeEdits,S.ocr]))await refreshNative(v.nativeEdits||[],v.ocr||[]);\n  Object.assign(S, v);\n  setDirty',1)
s=s.replace('const bytes = await rpc("save", {','let bytes = await rpc("save", {',1);pos=s.index('    const name =\n',s.index('async function savePDF'));s=s[:pos]+'    if(S.nativeEdits.length||S.ocr.length)bytes=new Uint8Array((await window.desktop.native({command:"apply",bytes,edits:S.nativeEdits,ocr:S.ocr})).bytes);\n'+s[pos:]
s=s.replace('页旋转设置。`,','页旋转设置、${S.nativeEdits.length} 个内容编辑、${S.ocr.length} 条 OCR 文字。`,');s=s.replace('    showTargetMarker();\n    clearTimeout(viewTimer);','    showTargetMarker();nativeUI?.overlay();\n    clearTimeout(viewTimer);')
pos=s.index('Object.assign(actions, {');s=s[:pos]+'''async function refreshNative(edits=S.nativeEdits,ocr=S.ocr){
 if(!window.desktop?.native)throw Error("内容编辑和 OCR 需要完整桌面运行包");
 const anchor=surface.capture();setBusy(true,"正在生成内容预览…");
 try{const bytes=edits.length||ocr.length?new Uint8Array((await window.desktop.native({command:"apply",bytes:S.bytes,edits,ocr})).bytes):new Uint8Array(S.bytes);
 const pdf=await pdfjs.getDocument({data:bytes,cMapUrl:new URL("./vendor/cmaps/",import.meta.url).href,cMapPacked:true,standardFontDataUrl:new URL("./vendor/standard_fonts/",import.meta.url).href,wasmUrl:new URL("./vendor/wasm/",import.meta.url).href,isEvalSupported:false,enableXfa:false}).promise;
 const old=S.pdf;surface.cancel(true);S.pdf=pdf;surface.signature="";await surface.refresh(anchor);await old.destroy();}finally{setBusy(false)}
}
const nativeUI=installNativeUI({S,surface,modal,closeModal,esc,commit,refreshNative,guarded,toast,pageRange,clone,descendants,writeFile,setCleanup:fn=>{modalCleanup=fn}});
'''+s[pos:];s=s.replace('Object.assign(actions, {','Object.assign(actions, {\n whitespace:nativeUI.whitespaceDialog,"edit-content":nativeUI.objectDialog,ocr:nativeUI.ocrDialog,"ocr-preview":nativeUI.toggleOCR,',1)
s=s.replace('          S.baseline = saved.baseline;','          S.nativeEdits ||= [];S.ocr ||= [];if(S.nativeEdits.length||S.ocr.length)await refreshNative();\n          S.baseline = saved.baseline;')
a=s.index('function batchDialog()');b=s.index('function ',a+len('function batchDialog()'));part=s[a:b];part=part.replace('let preview = null,','let preview = null, report=null,',1).replace('{ text: "取消", run: closeModal },','{ text:"取消",run:closeModal },{text:"导出完整修改报告",run:()=>{if(!preview||!report)throw Error("请先生成有效预览");return writeFile("Folio-batch-report.json",new TextEncoder().encode(JSON.stringify(report,null,2)),"json")}},',1).replace('      preview = out;','      report={rule,changes:describeChanges(S.nodes,out,rule)};preview = out;',1)
# Replace the old title-only mapping through its terminal semicolon.
x=part.index('      $("#batch-preview").innerHTML =');y=part.index(';',x);part=part[:x]+'''      $("#batch-preview").innerHTML=`<details><summary>完整规则参数</summary><pre>${esc(JSON.stringify(rule,null,2))}</pre></details>`+nativeUI.diffTable(report.changes.slice(0,80))'''+part[y:];s=s[:a]+part+s[b:]
s=s.replace('Math.min(6,','Math.min(12,').replace('Folio PDF Studio · 0.2.0','Folio PDF Studio · 0.3.0').replace('扫描件需先在其他工具中完成 OCR。','扫描件可先使用工具栏 OCR，再生成书签。').replace('此版本不提供任意正文重排、OCR、表单编辑或安全涂黑。','此版本支持基础文字/路径对象编辑与 OCR；不提供段落自动重排、表单编辑或安全涂黑。').replace('最多缓存 8 页，单页最多约 600 万像素。','最多缓存 8 页基础预览，高清分块按可见区域绘制，缩放期间保留已完成画面。')
s=s.replace('      const blob = await new Promise((r) =>\n        $("#pdf-canvas").toBlob(r, "image/png"),\n      );','''      const page=await S.pdf.getPage(S.page),base=page.getViewport({scale:1,rotation:surface.rotation(S.page)}),scale=Math.min(2,Math.sqrt(24000000/(base.width*base.height))),viewport=page.getViewport({scale,rotation:surface.rotation(S.page)}),c=document.createElement("canvas");c.width=Math.ceil(viewport.width);c.height=Math.ceil(viewport.height);await page.render({canvasContext:c.getContext("2d"),viewport,background:"white"}).promise;const blob=await new Promise(r=>c.toBlob(r,"image/png"));c.width=0;c.height=0;''')
s=s.replace('function settingsDialog() {','async function settingsDialog() {\n const software=await window.desktop?.graphics?.()||false;').replace('<button data-action="shortcuts">自定义快捷键…</button>','<label class="check"><input id="set-gpu" type="checkbox" ${software?"checked":""} ${window.desktop?.graphics?"":"disabled"}>显卡兼容：关闭硬件加速（重新启动后生效）</label><button data-action="shortcuts">自定义快捷键…</button>');a=s.index('async function settingsDialog');b=s.index('function helpDialog',a);part=s[a:b].replace('run: () => {','run: async () => {',1).replace('          Object.assign(settings, {','          if(window.desktop?.graphics)await window.desktop.graphics($("#set-gpu").checked);\n          Object.assign(settings, {',1);s=s[:a]+part+s[b:];p.write_text(s)
p=root/'src/index.html';s=p.read_text().replace('<span class="version">0.2</span>','<span class="version">0.3</span>').replace('><button data-action="batch"', '><button data-action="edit-content" data-doc>编辑内容</button><button data-action="ocr" data-doc>OCR</button><button data-action="ocr-preview" data-doc>文字预览</button><button data-action="whitespace" data-doc title="批量调整跳转顶部留白">留白</button><button data-action="batch"');p.write_text(s)
p=root/'file-store.cjs';s=p.read_text().replace('constructor(pick) {','constructor(pick,replace=fs.rename) {\n this.replace=replace;').replace('await fs.rename(tmp, file);','await this.replace(tmp,file);').replace('throw err;','const labels={EPERM:"目标文件只读、被占用或没有替换权限",EACCES:"没有目标目录的写入权限",EBUSY:"目标文件被占用",ENOSPC:"磁盘空间不足"};throw Error(`保存 ${path.basename(file)} 失败：${labels[err.code]||err.message}`);');p.write_text(s)
p=root/'main.cjs';s=p.read_text();pos=s.index('protocol.registerSchemesAsPrivileged');s=s[:pos]+'''const graphicsFile=path.join(app.getPath("userData"),"graphics.json");let softwareGraphics=false;try{softwareGraphics=JSON.parse(require("node:fs").readFileSync(graphicsFile,"utf8")).software===true}catch{}if(softwareGraphics)app.disableHardwareAcceleration();
'''+s[pos:];s=s.replace('let fileStore;','const {NativeBridge}=require("./native-bridge.cjs");const native=new NativeBridge(app.isPackaged?path.join(process.resourcesPath,"native"):path.join(__dirname,"native"));let fileStore;').replace('return r.canceled ? null : r.filePath;\n  });','return r.canceled ? null : r.filePath;\n  }, process.platform==="win32"?(source,target)=>native.replace(source,target):undefined);').replace('ipc("save", (data) => fileStore.save(data));','ipc("save", (data) => fileStore.save(data));\n ipc("native",data=>native.run(data));ipc("native-cancel",()=>native.cancel());\n ipc("graphics",async value=>{if(typeof value==="boolean"){await fs.mkdir(path.dirname(graphicsFile),{recursive:true});await fs.writeFile(graphicsFile,JSON.stringify({software:value}))}return softwareGraphics});').replace('app.on("window-all-closed", () => app.quit());','app.on("window-all-closed",()=>{native.cancel();app.quit()});');p.write_text(s)
p=root/'preload.cjs';s=p.read_text().replace('  fullscreen:', '  native:data=>ipcRenderer.invoke("native",data),cancelNative:()=>ipcRenderer.invoke("native-cancel"),graphics:value=>ipcRenderer.invoke("graphics",value),\n  fullscreen:');p.write_text(s)
