from pathlib import Path
p=Path(__file__).resolve().parents[1]/'src/viewer.mjs';s=p.read_text().replace('this.entries = new Map();','this.entries = new Map();this.fallback=new Map();this.tileSerial=0;');a=s.index('  cancel() {');b=s.index('  rotation(p)',a);s=s[:a]+'''  dispose(e){e.cancelled=true;e.task?.cancel();e.textTask?.cancel();for(const t of e.tiles?.values()||[])t.task?.cancel();e.shell.remove();for(const c of e.shell.querySelectorAll('canvas')){c.width=0;c.height=0}}
  cancel(keep=false){this.epoch++;this.tileSerial++;for(const [p,e] of this.entries){e.cancelled=true;e.task?.cancel();e.textTask?.cancel();for(const t of e.tiles?.values()||[])t.task?.cancel();if(keep&&e.shell.dataset.ready==='true'){if(this.fallback.has(p))this.dispose(this.fallback.get(p));for(const el of [e.shell,...e.shell.querySelectorAll('[id]')])el.removeAttribute('id');e.text.hidden=true;e.marks.hidden=true;e.draw.hidden=true;e.shell.querySelector('.target-marker')?.remove();e.shell.classList.add('page-fallback');e.shell.style.pointerEvents='none';this.fallback.set(p,e)}else this.dispose(e)}this.entries.clear();if(!keep){for(const e of this.fallback.values())this.dispose(e);this.fallback.clear()}}
'''+s[b:];s=s.replace('Math.min(6,','Math.min(12,');s=s.replace('this.signature = key;\n      this.cancel();','this.signature = key;\n      this.cancel(true);');s=s.replace('    this.restoreAnchor(anchor);','''    for(const [p,e] of this.fallback){const b=this.boxes.find(b=>b.page===p);if(!b){this.dispose(e);this.fallback.delete(p);continue}e.shell.style.left=b.x+'px';e.shell.style.top=b.y+'px';e.shell.style.transformOrigin='0 0';e.shell.style.transform=`scale(${b.w/e.b.w},${b.h/e.b.h})`}
    this.restoreAnchor(anchor);''',1)
a=s.index('    for (const [p, e] of this.entries)');b=s.index('    // Sequential render',a);s=s[:a]+'''    for(const [p,e] of this.entries)if(!keep.has(p)){this.dispose(e);this.entries.delete(p)}
    for(const [p,e] of this.fallback)if(!keep.has(p)){this.dispose(e);this.fallback.delete(p)}
'''+s[b:];s=s.replace('    if (b) this.activate(b.page);','    if (b) this.activate(b.page);this.scheduleTiles();',1);s=s.replace('    shell.append(canvas, text, marks, draw);',"    shell.style.background='transparent';const tileLayer=document.createElement('div');tileLayer.className='page-tiles';shell.append(tileLayer,text,marks,draw);");s=s.replace('const e = { shell, canvas, text, marks, draw, cancelled: false };','const e = { shell, canvas, text, marks, draw, tileLayer,tiles:new Map(),b:{...b},cancelled:false };');s=s.replace('          this.settings.quality,\n          Math.sqrt(6000000','          1,\n          Math.sqrt(1200000');s=s.replace('      const content = await p.getTextContent();',"      shell.prepend(canvas);shell.style.background='white';shell.dataset.ready='true';const old=this.fallback.get(b.page);if(old){this.dispose(old);this.fallback.delete(b.page)}\n      const content = await p.getTextContent();",1)
a=s.index('  activate(page) {');s=s[:a]+'''  scheduleTiles(){clearTimeout(this.tileTimer);const serial=++this.tileSerial;this.tileTimer=setTimeout(()=>this.renderTiles(serial).catch(this.onError),90)}
  async renderTiles(serial){const ratio=Math.min(devicePixelRatio||1,this.settings.quality||2),size=512,h=this.host;let bytes=0;for(const e of this.entries.values()){if(!e.page||e.cancelled||!e.viewport)continue;const b=e.b,v=e.viewport,wanted=new Set();for(let y=Math.max(0,Math.floor((h.scrollTop-b.y)/size));y<=Math.min(Math.ceil(v.height/size)-1,Math.floor((h.scrollTop+h.clientHeight-b.y)/size));y++)for(let x=Math.max(0,Math.floor((h.scrollLeft-b.x)/size));x<=Math.min(Math.ceil(v.width/size)-1,Math.floor((h.scrollLeft+h.clientWidth-b.x)/size));x++)wanted.add(x+':'+y);for(const [key,t] of e.tiles)if(!wanted.has(key)||!t.ready){t.task?.cancel();t.canvas.remove();t.canvas.width=0;e.tiles.delete(key)}for(const key of wanted){if(serial!==this.tileSerial||e.cancelled)return;if(e.tiles.has(key))continue;const [ix,iy]=key.split(':').map(Number),x=ix*size,y=iy*size,w=Math.min(size,v.width-x),hh=Math.min(size,v.height-y),c=document.createElement('canvas');c.width=Math.ceil(w*ratio);c.height=Math.ceil(hh*ratio);c.style.cssText=`position:absolute;left:${x}px;top:${y}px;width:${w}px;height:${hh}px`;const t={canvas:c};e.tiles.set(key,t);try{t.task=e.page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,transform:[ratio,0,0,ratio,-x*ratio,-y*ratio],background:'white'});await t.task.promise;if(serial!==this.tileSerial||e.cancelled){if(e.tiles.get(key)===t)e.tiles.delete(key);c.width=0;continue}e.tileLayer.append(c);t.ready=true}catch(err){if(e.tiles.get(key)===t)e.tiles.delete(key);c.width=0;if(err.name!=='RenderingCancelledException')throw err}}bytes+=[...e.tiles.values()].reduce((n,t)=>n+t.canvas.width*t.canvas.height*4,0);e.shell.dataset.sharp='true'}this.tileBytes=bytes}
'''+s[a:];p.write_text(s)
